# Generated by Django 3.2.8 on 2021-10-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(default='')),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
