# Generated by Django 3.2.8 on 2021-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makanan', models.TextField(default='', max_length=200)),
                ('jenismakanan', models.CharField(max_length=20)),
                ('minuman', models.TextField(default='', max_length=200)),
                ('harga', models.IntegerField(default=0)),
                ('jumlah', models.IntegerField(default=0)),
            ],
        ),
    ]
