# Generated by Django 3.2.8 on 2021-10-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='nama',
            new_name='makanan',
        ),
    ]
