# Generated by Django 3.2.8 on 2021-10-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_jenisminuman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='jumlah',
            new_name='jumlahmakanan',
        ),
        migrations.AddField(
            model_name='task',
            name='jumlahminuman',
            field=models.IntegerField(default=0),
        ),
    ]
