# Generated by Django 3.2.8 on 2021-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_nama_task_makanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='makanan',
            field=models.TextField(max_length=200),
        ),
    ]
