# Generated by Django 3.2.8 on 2021-10-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_makanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='minuman',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='makanan',
            field=models.TextField(default='', max_length=200),
        ),
    ]
