# Generated by Django 3.2.8 on 2021-10-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20211014_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='harga',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='jumlah',
            field=models.IntegerField(default=''),
        ),
    ]
