# Generated by Django 3.2.8 on 2021-10-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20211014_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='jenismakanan',
            field=models.IntegerField(default=''),
        ),
    ]
