# Generated by Django 3.2.8 on 2021-10-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_jenismakanan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='jenismakanan',
            new_name='jenis',
        ),
    ]
