# Generated by Django 3.2.8 on 2021-10-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_rename_jenismakanan_task_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='jenis',
            field=models.CharField(default='', max_length=20),
        ),
    ]
