# Generated by Django 3.2.8 on 2021-10-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_jenis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='jenis',
        ),
    ]
